### ISSUE TITLE
NewTabPageSetFeedType does not exist

### ISSUE THREAD

**Issue by oleesch** [MicrosoftDocs/EdgeEnterprise#11] opened 2019-09-13 14:01 UTC
The policy "NewTabPageLocation" is referencing a policy called "NewTabPageSetFeedType". As far as I can tell that policy doesn't exist (can't find it anywhere in the ADMX files or on this page).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1cd3ad5-bb4a-54ff-84e7-18ca0b11368f
* Version Independent ID: 984abd8f-45eb-737b-ad74-07ec8261f9eb
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-policies#feedback)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/EdgeEnterprise-pr/blob/live/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by FreekBloemhof** [comment] 2019-09-20 09:12
Duplicate of #3

**Comment by Brianalt-Msft** [comment] 2019-09-23 15:50
I logged a bug to about the missing policy. Thank you for reporting it.

**Comment by Brianalt-Msft** [comment] 2020-02-26 19:24
NewTabPageSetFeedType is now supported.

**Closed by Brianalt-Msft** 2020-02-26 19:24 UTC
